config/routes.rb
require 'sidekiq/web'
require 'admin_constraint'

Rails.application.routes.draw do
    root   'static_pages#home'

    get    'help'    => 'static_pages#help'
    get    'about'   => 'static_pages#about'
    get    'contact' => 'static_pages#contact'
    get    'signup'  => 'users#new'
    get    'login'   => 'sessions#new'
    post   'login'   => 'sessions#create'
    delete 'logout'  => 'sessions#destroy'

    shallow do
        resources :users do
            resources :document_stores do
                resources :documents
            end

            member do
                post :toggle_activation
                get  :following, :followers
            end
        end
    end

    resources :account_activations, only: [:edit]
    resources :password_resets,     only: [:new, :create, :edit, :update]
    resources :microposts,          only: [:create, :destroy]
    resources :relationships,       only: [:create, :destroy]

    mount Sidekiq::Web => '/sidekiq', :constraints => AdminConstraint.new

    shallow do
        namespace :api, defaults: { format: :json },
                        path: '/',
                        constraints: { subdomain: 'api' } do
            namespace :v1 do
                resources :document_stores, only: [:index] do
                    resources :documents, only: [:index] do
                        get 'html'
                        resources :document_markers, only: [:index, :show, :create]
                    end
                end
            end
        end
    end

end

app/models/document.rb
class Document < ActiveRecord::Base

    belongs_to :document_store

    has_many :document_markers

    validates :document_store, presence: true
    validates :name, presence: true, length: { maximum: 50 }

    mount_uploader :file, FileUploader

    # Convert to HTML after saving document.
    after_save :convertPdf2Html

    def html_absolute_path
        p = Pathname.new(self.file.path)
        File.join( p.dirname, p.basename("pdf") ) + "html"
    end

    # Relative path from app directory.
    def html_relative_path
        p = Pathname.new(self.file.to_s)
        File.join( 'public', p.dirname, p.basename("pdf") ) + "html"
    end

    private
    def convertPdf2Html
        Rails.logger.info "Document::convertPDF2HTML"

        in_path  = self.file.path
        out_path = self.html_relative_path  # Kristin gem requires this
                                            # relative path for the outfile.

        if File.exists?(in_path)
            ConvertPdfToHtmlJob.perform_later(in_path, out_path)
        end
    end
end

app/controllers/api/v1/documents_controller.rb
module API
    class V1::DocumentsController < ApplicationController

        def index
            respond_to do |format|
                format.json { @documents = DocumentStore.find(params[:document_store_id]).documents }
            end
        end

        def html
            render body: File.read(Document.find(params[:document_id]).html_absolute_path)
        end

    end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  #before_action :logged_in_user
  #before_action :admin_user,         only: [:edit, :destroy]
  before_action :set_document_store, only: [:index, :new, :create]
  before_action :set_document,       only: [:show, :edit, :update, :destroy]
  before_action :correct_user,       only: [:show, :edit, :update, :destroy]

  # GET /document_stores/:document_store_id/documents
  # GET /document_stores/:document_store_id/documents.json
  def index
    @documents = @document_store.documents
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
  end

  # GET /document_stores/:document_store_id/documents/new
  def new
    @document = @document_store.documents.build
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /document_stores/:document_store_id/documents
  # POST /document_stores/:document_store_id/documents.json
  def create
    @document = @document_store.documents.build(document_params)

    respond_to do |format|
      if @document.save
        flash[:success] = 'Document was successfully created.'
        format.html { redirect_to @document }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        flash[:success] = 'Document was successfully updated.'
        format.html { redirect_to @document }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      flash[:success] = 'Document was successfully destroyed.'
      format.html { redirect_to document_store_documents_url(@document.document_store) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params
      params.require(:document).permit(:document_store_id, :name, :description, :file)
    end

    def set_document_store
      @document_store = DocumentStore.find(params[:document_store_id])
    end

    def correct_user
      @document = current_user.documents.find_by(id: params[:id])
      if @document.nil?
        flash[:danger] = "You do not have access to the requested resource."
        redirect_to root_url
      end
    end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>

<div class="form-inputs">
  <%= f.association :document_store, collection: current_user.document_stores %>
  <%= f.input :name %>
  <%= f.input :description %>
</div>
<span class="file">
  <%= f.file_field :file, accept: 'application/pdf' %>
</span>

<div class="form-actions">
  <%= f.button :submit, class: "btn btn-primary" %>
</div>

<script type="text/javascript">
  $('#document_file').bind('change', function() {
    size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 100) {
      alert('Maximum file size is 100MB. Please choose a smaller file.');
    }
  });
</script>

app/views/documents/edit.html.erb
<h1>Editing Document</h1>


<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= simple_form_for(@document, html: { multipart: true }) do |f| %>
      <%= render 'fields', f: f %>
    <% end %>
  </div>
</div>

<%= link_to 'Show', @document %> |
<%= link_to 'Back', document_store_path(@document.document_store) %>

app/views/documents/index.html.erb
<h1>Listing Documents</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Document store</th>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @documents.each do |document| %>
      <tr>
        <td><%= document.document_store.name %></td>
        <td><%= document.name %></td>
        <td><%= document.description %></td>
        <td><%= link_to 'Show', document %></td>
        <td><%#= link_to 'Edit', edit_document_path(document) %></td>
        <td><%= link_to 'Delete', document, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Document', new_document_store_document_path %>

app/views/documents/new.html.erb
<h1>Add Document</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= simple_form_for([@document.document_store, @document], html: { multipart: true }) do |f| %>
      <%= render 'fields', f: f %>
    <% end %>

  </div>
</div>

<%= link_to 'Back', document_store_documents_path(@document_store) %>

app/views/documents/old.show.html.erb
<p>
  <strong>Document store:</strong>
  <%= @document.document_store.name %>
</p>

<p>
  <strong>Name:</strong>
  <%= @document.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @document.description %>
</p>

<p>
  <strong>File:</strong>
  <%= @document.file %>
</p>

<%= link_to 'Edit', edit_document_path(@document) %> |
<%= link_to 'Back', document_store_documents_path(@document.document_store) %>

app/views/documents/show.html.erb
<p>
  <strong>Document store:</strong>
  <%= @document.document_store.name %>
</p>

<p>
  <strong>Name:</strong>
  <%= @document.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @document.description %>
</p>

<p>
  <strong>File:</strong>
  <%= @document.file %>
</p>

<p>
  <strong>Preview:</strong>
</p>
<div id="preview">
  <h3><a href="#" id="btnRange">Display Range</a> |
    <a href="#" id="btnMark">Mark Range</a></h3>
  <%# file_path = @document.file.file.file[0..-5] + "-html.html" %>
  <%
    file_path = @document.file.to_s
    dirname = File.dirname(file_path)
    basename = File.basename(file_path, ".pdf")
    html_path = File.join(Rails.public_path, dirname, basename) + ".html"
  %>
  <%= render file: html_path %>
</div>

<!-- %= link_to 'Edit', edit_document_path(@document) %> | -->
<%= link_to 'Back', document_store_documents_path(@document.document_store) %>