config/routes.rb
require 'sidekiq/web'
require 'admin_constraint'

Rails.application.routes.draw do
    root   'static_pages#home'

    get    'help'    => 'static_pages#help'
    get    'about'   => 'static_pages#about'
    get    'contact' => 'static_pages#contact'
    get    'signup'  => 'users#new'
    get    'login'   => 'sessions#new'
    post   'login'   => 'sessions#create'
    delete 'logout'  => 'sessions#destroy'

    shallow do
        resources :users do
            resources :document_stores do
                resources :documents
            end

            member do
                post :toggle_activation
                get  :following, :followers
            end
        end
    end

    resources :account_activations, only: [:edit]
    resources :password_resets,     only: [:new, :create, :edit, :update]
    resources :microposts,          only: [:create, :destroy]
    resources :relationships,       only: [:create, :destroy]

    mount Sidekiq::Web => '/sidekiq', :constraints => AdminConstraint.new

    shallow do
        namespace :api, defaults: { format: :json },
                        path: '/',
                        constraints: { subdomain: 'api' } do
            namespace :v1 do
                resources :document_stores, only: [:index] do
                    resources :documents, only: [:index] do
                        get 'html'
                        resources :document_markers, only: [:index, :show, :create]
                    end
                end
            end
        end
    end

end

app/models/document_store.rb
class DocumentStore < ActiveRecord::Base

  before_validation(on: :create) { generate_access_token }

  belongs_to :user

  has_many :documents, dependent: :destroy

  validates :user, presence: true
  validates :name, presence: true, length: { maximum: 50 }
  validates :access_token, presence: true

  private

  def generate_access_token
    self.access_token = loop do
      random_token = SecureRandom.hex
      break random_token unless self.class.exists?(access_token: random_token)
    end
  end
end

app/controllers/api/v1/document_stores_controller.rb
module API
  class V1::DocumentStoresController < ApplicationController
    before_action :restrict_access

    def index
      respond_to do |format|
        format.json { @document_stores }
      end
    end

    private

    def restrict_access
      @lsof_access_tokens = params[:access_token].split(",")
      @document_stores    = DocumentStore.where(access_token: @lsof_access_tokens)
      head :unauthorized unless @document_stores
    end
  end
end

app/controllers/document_stores_controller.rb
class DocumentStoresController < ApplicationController
  before_action :logged_in_user
  before_action :set_user,           only: [:index, :new, :create]
  before_action :set_document_store, only: [:show, :edit, :update, :destroy]
  before_action :correct_user,       only: [:show, :edit, :update, :destroy]

  # GET /users/:user_id/document_stores
  # GET /users/:user_id/document_stores.json
  def index
    @document_stores = @user.document_stores
  end

  # GET /document_stores/1
  # GET /document_stores/1.json
  def show
    @documents = @document_store.documents
  end

  # GET /users/:user_id/document_stores/new
  def new
    @document_store = @user.document_stores.build
  end

  # GET /document_stores/1/edit
  def edit
  end

  # POST /users/:user_id/document_stores
  # POST /users/:user_id/document_stores.json
  def create
    @document_store = @user.document_stores.build(document_store_params)

    respond_to do |format|
      if @document_store.save
        format.html { redirect_to @document_store, notice: 'Document store was successfully created.' }
        format.json { render :show, status: :created, location: @document_store }
      else
        format.html { render :new }
        format.json { render json: @document_store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /document_stores/1
  # PATCH/PUT /document_stores/1.json
  def update
    respond_to do |format|
      if @document_store.update(document_store_params)
        format.html { redirect_to @document_store, notice: 'Document store was successfully updated.' }
        format.json { render :show, status: :ok, location: @document_store }
      else
        format.html { render :edit }
        format.json { render json: @document_store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /document_stores/1
  # DELETE /document_stores/1.json
  def destroy
    @document_store.destroy
    respond_to do |format|
      format.html { redirect_to user_document_stores_url(@document_store.user_id), notice: 'Document store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Before actions

    # Use callbacks to share common setup or constraints between actions.
    def set_document_store
      @document_store = DocumentStore.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_store_params
      params.require(:document_store).permit(:user_id, :name)
    end

    def set_user
      @user = User.find(params[:user_id])
    end

    def correct_user
      @document_store = current_user.document_stores.find_by(id: params[:id])
      if @document_store.nil?
        flash[:danger] = "You do not have access to the requested resource."
        redirect_to root_url
      end
    end
end

app/helpers/document_stores_helper.rb
module DocumentStoresHelper
end

app/views/document_stores/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>

<div class="form-inputs">
  <!-- The association below should be scoped to perhaps a team? -->
  <%= f.association :user, collection: User.where(id: @document_store.user.id) %>
  <%= f.input :name, label: 'Document Store Name' %>
</div>

<div class="form-actions">
  <%= f.button :submit, class: 'btn btn-primary' %>
</div>

app/views/document_stores/edit.html.erb
<h1>Editing Document Store</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= simple_form_for(@document_store) do |f| %>
      <%= render 'fields', f: f %>
    <% end %>

  </div>
</div>

<%= link_to 'Show', @document_store %> |
<%= link_to 'Back', user_document_stores_path(@document_store.user) %>

app/views/document_stores/index.html.erb
<h1>Listing Document Stores</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>User</th>
      <th>Document Store</th>
      <th>Access Token</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @document_stores.each do |document_store| %>
      <tr>
        <td><%= document_store.user.name %></td>
        <td><%= link_to "#{document_store.name}", document_store %></td>
        <td><%= document_store.access_token %></td>
        <td><%= link_to 'Edit', edit_document_store_path(document_store) %></td>
        <td><%= link_to 'Delete', document_store, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Document store', new_user_document_store_path(@user.id) %>

app/views/document_stores/new.html.erb
<h1>New Document Store</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= simple_form_for([@document_store.user, @document_store]) do |f| %>
      <%= render 'fields', f: f %>
    <% end %>

  </div>
</div>

<%= link_to 'Back', user_document_stores_path(@document_store.user) %>

app/views/document_stores/show.html.erb
<p>
  <strong>User:</strong>
  <%= @document_store.user.name %>
</p>

<p>
  <strong>Document Store Name:</strong>
  <%= @document_store.name %>
</p>

<p>
  <strong>Document List:</strong>

  <% if @documents.present? %>
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Document name</th>
          <th>Document description</th>
        </tr>
      </thead>
      <tbody>
        <% @documents.each do |document| %>
          <tr>
            <td><%= link_to document.name, document %></td>
            <td><%= document.description %></td>
            <td><%= link_to "Edit", edit_document_path(document) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <em>No documents found.</em>
  <% end %>

  <%= link_to document_store_documents_path(@document_store) do %>
    <button type="button" class="btn btn-default btn-xs" aria-label="Left Align">
      <span class="glyphicon glyphicon-folder-open" aria-hidden="true"></span> Manage Documents
    </button>
  <% end %>
</p>

<%= link_to 'Edit', edit_document_store_path(@document_store) %> |
<%= link_to 'Back', user_document_stores_path(@document_store.user) %>