config/routes.rb
require 'sidekiq/web'
require 'admin_constraint'

Rails.application.routes.draw do
    root   'static_pages#home'

    get    'help'    => 'static_pages#help'
    get    'about'   => 'static_pages#about'
    get    'contact' => 'static_pages#contact'
    get    'signup'  => 'users#new'
    get    'login'   => 'sessions#new'
    post   'login'   => 'sessions#create'
    delete 'logout'  => 'sessions#destroy'

    shallow do
        resources :users do
            resources :document_stores do
                resources :documents
            end

            member do
                post :toggle_activation
                get  :following, :followers
            end
        end
    end

    resources :account_activations, only: [:edit]
    resources :password_resets,     only: [:new, :create, :edit, :update]
    resources :microposts,          only: [:create, :destroy]
    resources :relationships,       only: [:create, :destroy]

    mount Sidekiq::Web => '/sidekiq', :constraints => AdminConstraint.new

    shallow do
        namespace :api, defaults: { format: :json },
                        path: '/',
                        constraints: { subdomain: 'api' } do
            namespace :v1 do
                resources :document_stores, only: [:index] do
                    resources :documents, only: [:index] do
                        get 'html'
                        resources :document_markers, only: [:index, :show, :create]
                    end
                end
            end
        end
    end

end

app/views/layouts/_footer.html.erb
    <footer class="footer">
      <small>
        The <a href="http://daa.infalliblekitty.com/">Data Abstraction Assistant</a>
        by <a href="http://www.cebm.brown.edu/">CEBM Brown</a>
      </small>
      <nav>
        <ul>
          <li><%= link_to "About",   about_path %></li>
          <li><%= link_to "Contact", contact_path %></li>
          <li><a href="http://www.cebm.brown.edu/">News</a></li>
        </ul>
      </nav>
    </footer>

app/views/layouts/_header.html.erb
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Data Abstraction Assistant", root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",   root_path %></li>
            <li><%= link_to "Help",   help_path %></li>
            <% if logged_in? %>
              <% if current_user.admin? %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    Admin Tools <b class="caret"></b>
                  </a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "Users", users_path %></li>
                    <li><%= link_to "Sidekiq", sidekiq_web_path %></li>
                  </ul>
                </li>
              <% end %><!-- if current_user.admin? -->
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", current_user %></li>
                  <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Log out", logout_path, method: "delete" %>
                  </li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to "Log in", login_path %></li>
            <% end %>
          </ul><!-- /.nav .navbar-nav .navbar-right -->
        </nav>
      </div>
    </header>

app/views/layouts/_shim.html.erb
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>